<?php


namespace iyoule\Database\Eloquent;


use \InvalidArgumentException;
use Illuminate\Database\Eloquent\Model;
use iyoule\BizSpace\Biz;
use iyoule\Reflection\ReflectionClass;

/**
 * Class Mapper
 * @property
 * @package iyoule\Database\Eloquent
 * @mixin \Eloquent
 */
abstract class Mapper extends Model
{


    /**
     * @param $biz
     * @return array
     */
    private function biz2Array($biz)
    {
        if ($biz instanceof Biz) {
            try{
                return $biz->serialize2db();
            }catch (\ReflectionException $e){
                return [];
            }
        }
        if (is_object($biz) && method_exists('biz', 'toArray')) {
            return $biz->toArray();
        }
        if (!is_array($biz)) {
            throw new \InvalidArgumentException("param is must array");
        }
        return $biz;
    }

    /**
     * @param array|Biz $attributes
     * @return Model
     */
    public function fill($attributes)
    {
        return parent::fill($this->biz2Array($attributes)); // TODO: Change the autogenerated stub
    }


    public function __call($method, $parameters)
    {
        $args = [];
        foreach ($parameters as $parameter) {
            if ($parameter instanceof Biz) {
                $args[] = $parameter->serialize2db();
            } else {
                $args[] = $parameter;
            }
        }
        return parent::__call($method, $args); // TODO: Change the autogenerated stub
    }


    /**
     * @param $class
     * @return mixed
     */
    public function toBiz($class)
    {
        try {
            if (!class_exists($class) || !(new ReflectionClass($class))->isSubclassOf(Biz::class)) {
                throw new InvalidArgumentException("classname must be iyoule\\BizSpace\\Biz of class");
            }
            return call_user_func([$class, 'unSerialize'], $this->toArray());
        } catch (\ReflectionException $e) {
            throw new InvalidArgumentException("classname must be iyoule\\BizSpace\\Biz of class");
        }
    }

}